### ISSUE TITLE
请问一下在运行Python runxxx.py这一步时出现一下错误应该怎么解决

### ISSUE THREAD

**Issue by huang6668** [Derekabc/MARL_CAVs#19]
Traceback (most recent call last):
  File "run_mappo.py", line 227, in <module>
    train(args)
  File "run_mappo.py", line 81, in train
    env = gym.make('merge-multi-agent-v0')
  File "/home/huang/miniconda3/envs/marl_cav/lib/python3.8/site-packages/gym/envs/registration.py", line 569, in make
    _check_version_exists(ns, name, version)
  File "/home/huang/miniconda3/envs/marl_cav/lib/python3.8/site-packages/gym/envs/registration.py", line 219, in _check_version_exists
    _check_name_exists(ns, name)
  File "/home/huang/miniconda3/envs/marl_cav/lib/python3.8/site-packages/gym/envs/registration.py", line 197, in _check_name_exists
    raise error.NameNotFound(
gym.error.NameNotFound: Environment merge-multi-agent doesn't exist.

**Comment by DongChen06** [comment]
could you try to run the code under MARL_CAVS/MARL?

**Comment by huang6668** [comment]
I was able to run it after downgrading the GYM version, but encountered the same situation as another problem in Issues

**Comment by huang6668** [comment]
I want to express my sincere gratitude for your invaluable assistance in resolving the problem. Thank you very much
