### ISSUE TITLE
I have this problem when running both run_maacktr.py and run_mappo.py. It doesn't appear when running run_madqn, but it runs very slowly

### ISSUE THREAD

**Issue by Jonyian** [Derekabc/MARL_CAVs#20]
ERROR:root:Can not find checkpoint for ./results/Apr_25_03_15_06/models/
C:\Users\60438\Desktop\MARL_CAVs-main\MARL\single_agent\Model_common.py:21: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  out = self.output_act(self.fc3(out))
Traceback (most recent call last):
  File "C:\Users\60438\Desktop\MARL_CAVs-main\MARL\run_mappo.py", line 227, in <module>
    train(args)
  File "C:\Users\60438\Desktop\MARL_CAVs-main\MARL\run_mappo.py", line 133, in train
    mappo.interact()
  File "C:\Users\60438\Desktop\MARL_CAVs-main\MARL\MAPPO.py", line 113, in interact
    actions.append([index_to_one_hot(a, self.action_dim) for a in action])
  File "C:\Users\60438\Desktop\MARL_CAVs-main\MARL\MAPPO.py", line 113, in <listcomp>
    actions.append([index_to_one_hot(a, self.action_dim) for a in action])
  File "C:\Users\60438\Desktop\MARL_CAVs-main\MARL\common\utils.py", line 37, in index_to_one_hot
    one_hot = np.zeros((len(index), dim))
TypeError: object of type 'numpy.int32' has no len()

进程已结束,退出代码1

**Comment by huang6668** [comment]
我也出现了同样的问题

**Comment by DongChen06** [comment]
could you look at the issue: https://github.com/DongChen06/MARL_CAVs/issues/4

**Comment by Jonyian** [comment]
十分感谢您的回答，祝您科研顺利~
