### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Yzhtc** [Derekabc/MARL_CAVs#30]
**Hello, may I ask what are the reasons for the following errors and how to solve them？**
Connected to pydev debugger (build 221.5787.24)
Backend QtAgg is interactive backend. Turning interactive mode on.
Traceback (most recent call last):
  File "D:\SoftWare\Anaconda3\envs\pytorch\lib\site-packages\gym\envs\registration.py", line 138, in spec
    return self.env_specs[id]
KeyError: 'merge-multi-agent-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SoftWare\Pycharm\PyCharm Community Edition 2022.1.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1491, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\SoftWare\Pycharm\PyCharm Community Edition 2022.1.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/H/Desktop/MARL_CAVs-main/MARL_CAVs-main/MARL/run_madqn.py", line 72, in <module>
    run()
  File "C:/Users/H/Desktop/MARL_CAVs-main/MARL_CAVs-main/MARL/run_madqn.py", line 31, in run
    env = gym.make('merge-multi-agent-v0')
  File "D:\SoftWare\Anaconda3\envs\pytorch\lib\site-packages\gym\envs\registration.py", line 200, in make
    return registry.make(id, **kwargs)
  File "D:\SoftWare\Anaconda3\envs\pytorch\lib\site-packages\gym\envs\registration.py", line 104, in make
    spec = self.spec(path)
  File "D:\SoftWare\Anaconda3\envs\pytorch\lib\site-packages\gym\envs\registration.py", line 183, in spec
    raise error.UnregisteredEnv("No registered env with id: {}".format(id))
gym.error.UnregisteredEnv: No registered env with id: merge-multi-agent-v0
python-BaseException

Process finished with exit code -1073741510 (0xC000013A: interrupted by Ctrl+C)

**Comment by DongChen06** [comment]
Hi, thanks for your interest. Could you check the closed issues? There are similar issues and potential solutions. Thanks

**Comment by Yzhtc** [comment]
> Hi, thanks for your interest. Could you check the closed issues? There are similar issues and potential solutions. Thanks

Thank you for your answer！

**Comment by Yzhtc** [comment]
Sorry, I have made the directory as the source directory, but the following error still occurs?
![111](https://github.com/DongChen06/MARL_CAVs/assets/58619404/b12e5433-4de4-487f-84d2-c0174d071a6a)

**Comment by DongChen06** [comment]
OO, you used Windows. Can you try to run the codes use terminal under the
directory MARL

**Comment by Yzhtc** [comment]
> Hi, thanks for your interest. Could you check the closed issues? There are similar issues and potential solutions. Thanks
Hello, I know this is not an error. I would like to ask how I can modify the code to make these UserWarnings disappear.
![222](https://github.com/DongChen06/MARL_CAVs/assets/58619404/2265bdc1-0fe3-4fdd-8c3e-98a0471d5056)

**Comment by DongChen06** [comment]
according to the message, you may modify the code with the suggestion, adding a dimension dim=x

**Comment by Yzhtc** [comment]
> according to the message, you may modify the code with the suggestion, adding a dimension dim=x
Thanks again for your answer, I have solved the problem, have a nice day😊
