### ISSUE TITLE
TypeError: RandomNumberGenerator._generator_ctor() takes from 0 to 1 positional arguments but 2 were given

### ISSUE THREAD

**Issue by caixxuan** [Derekabc/MARL_CAVs#33]
PS C:\Users\CAIXUAN\Downloads\MARL_CAVs-main(1)\MARL_CAVs-main\MARL> python run_mappo.py
ERROR:root:Can not find checkpoint for ./results/Jan_27_12_42_16/models/
C:\Users\CAIXUAN\Downloads\MARL_CAVs-main(1)\MARL_CAVs-main\MARL\single_agent\Model_common.py:21: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  out = self.output_act(self.fc3(out))
Traceback (most recent call last):
  File "C:\Users\CAIXUAN\Downloads\MARL_CAVs-main(1)\MARL_CAVs-main\MARL\run_mappo.py", line 227, in <module>
    train(args)
  File "C:\Users\CAIXUAN\Downloads\MARL_CAVs-main(1)\MARL_CAVs-main\MARL\run_mappo.py", line 133, in train
    mappo.interact()
  File "C:\Users\CAIXUAN\Downloads\MARL_CAVs-main(1)\MARL_CAVs-main\MARL\MAPPO.py", line 112, in interact
    next_state, global_reward, done, info = self.env.step(tuple(action))
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CAIXUAN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gym\wrappers\order_enforcing.py", line 37, in step
    return self.env.step(action)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CAIXUAN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gym\wrappers\step_api_compatibility.py", line 52, in step
    step_returns = self.env.step(action)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CAIXUAN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gym\wrappers\env_checker.py", line 37, in step
    return env_step_passive_checker(self.env, action)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CAIXUAN\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\gym\utils\passive_env_checker.py", line 222, in env_step_passive_checker
    result = env.step(action)
             ^^^^^^^^^^^^^^^^
  File "C:\Users\CAIXUAN\Downloads\MARL_CAVs-main(1)\MARL_CAVs-main\MARL\../highway-env\highway_env\envs\merge_env_v1.py", line 127, in step
    obs, reward, done, info = super().step(action)
                              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CAIXUAN\Downloads\MARL_CAVs-main(1)\MARL_CAVs-main\MARL\../highway-env\highway_env\envs\common\abstract.py", line 456, in step
    self.new_action = self.safety_supervisor(action)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CAIXUAN\Downloads\MARL_CAVs-main(1)\MARL_CAVs-main\MARL\../highway-env\highway_env\envs\common\abstract.py", line 285, in safety_supervisor      
    env_copy = copy.deepcopy(self)
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\copy.py", line 153, in deepcopy
    y = copier(memo)
        ^^^^^^^^^^^^
  File "C:\Users\CAIXUAN\Downloads\MARL_CAVs-main(1)\MARL_CAVs-main\MARL\../highway-env\highway_env\envs\common\abstract.py", line 710, in __deepcopy__
    setattr(result, k, copy.deepcopy(v, memo))
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2032.0_x64__qbz5n2kfra8p0\Lib\copy.py", line 265, in _reconstruct
    y = func(*args)
        ^^^^^^^^^^^
TypeError: RandomNumberGenerator._generator_ctor() takes from 0 to 1 positional arguments but 2 were given

Looking for help, 3q!
![图片](https://github.com/DongChen06/MARL_CAVs/assets/110223255/85743ada-822c-40ae-baed-e2f01e7f6c3a)

**Comment by caixxuan** [comment]
I've run this in Windows

**Comment by DongChen06** [comment]
@caixxuan  Hi, thanks for your question. I think the error may be related to the version of libraries, such as Numpy, could you try to downgrade the libraries and try again? https://github.com/DongChen06/MARL_CAVs/issues/18

**Comment by caixxuan** [comment]
![图片](https://github.com/DongChen06/MARL_CAVs/assets/110223255/965274b8-0827-45d4-ae1c-4b2f1be909a8)
![图片](https://github.com/DongChen06/MARL_CAVs/assets/110223255/e3a0eeb0-8cee-4712-9e3f-5f8bc0448c7c)
I have reinit a new conda environment, and install the requirements as your suggest. But I meet a new error "    x = np.array(x, dtype=np.float64).tolist()
ValueError: setting an array element with a sequence."

**Comment by caixxuan** [comment]
> @caixxuan Hi, thanks for your question. I think the error may be related to the version of libraries, such as Numpy, could you try to downgrade the libraries and try again? #18

![图片](https://github.com/DongChen06/MARL_CAVs/assets/110223255/965274b8-0827-45d4-ae1c-4b2f1be909a8)
![图片](https://github.com/DongChen06/MARL_CAVs/assets/110223255/e3a0eeb0-8cee-4712-9e3f-5f8bc0448c7c)
I have reinit a new conda environment, and install the requirements as your suggest. But I meet a new error "    x = np.array(x, dtype=np.float64).tolist()
ValueError: setting an array element with a sequence."

**Comment by caixxuan** [comment]
![图片](https://github.com/DongChen06/MARL_CAVs/assets/110223255/e692c4d6-dae1-4f21-84fd-ae4e2b23Before da07)
Before the above error, I have change "len(index)" to "len(range(index))", or the error will exist

**Comment by caixxuan** [comment]
![图片](https://github.com/DongChen06/MARL_CAVs/assets/110223255/18bfbb72-8ad5-4fd6-b95d-09b2a7c8a9f5)
Before the above error, I have meet this error, But I change the "len(index)" to "len(range(index))", I dont know if it is true

**Comment by caixxuan** [comment]
![图片](https://github.com/DongChen06/MARL_CAVs/assets/110223255/8abc54ff-e308-4ff1-a4db-7d092c3f6a8a)
Intesting, run_madqp.py can run successfully! but another two cannot

**Comment by DongChen06** [comment]
> ![图片](https://private-user-images.githubusercontent.com/110223255/301074385-18bfbb72-8ad5-4fd6-b95d-09b2a7c8a9f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MTYwODYsIm5iZiI6MTcwNjcxNTc4NiwicGF0aCI6Ii8xMTAyMjMyNTUvMzAxMDc0Mzg1LTE4YmZiYjcyLThhZDUtNGZkNi1iOTVkLTA5YjJhN2M4YTlmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMVQxNTQzMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjBkOGQ3OGFhNWNmY2I0N2JjZGU0M2JiNGQxMTIxMWNhYTYzNWJlYzc3ZjQ4Y2IxZDZlOTUwNjliM2E3MmQwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AQEXY-WvgVMPaN02LnPLl5dewOBLlBYUsyoUXuaZWZA) Before the above error, I have meet this error, But I change the "len(index)" to "len(range(index))", I dont know if it is true

Hi, you may find the solutions with this issue in the existing issues.

**Comment by caixxuan** [comment]
![图片](https://github.com/DongChen06/MARL_CAVs/assets/110223255/f25e1b36-035a-410b-805e-a0445aed2817)
This problem still exist, I dont know how to fix it

**Comment by caixxuan** [comment]
![Screenshot from 2024-02-01 17-18-06](https://github.com/DongChen06/MARL_CAVs/assets/110223255/826bb49c-d2ad-4422-a6d8-a523b5a87b6d)
If I transform these codes to Linux, run_ma2c is ok, but others will report this above issue? I dont know how to fix it?

**Comment by DongChen06** [comment]
It's an issue with your devices, you may transform the tensors to CPU.
