### ISSUE TITLE
Exception: Sorry, no pretrained models

### ISSUE THREAD

**Issue by AZ1229-forever** [Derekabc/MARL_CAVs#53]
您好，我运行run_mappo.py后出现以下报错，运行之后会出现result文件夹，但是models里面没有文件，应该如何解决呢
![Uploading 1.png…]()
以下是我的环境配置[
![Uploading 2.png…]()
](url)

**Comment by DongChen06** [comment]
Hi, the images were not uploaded correctly. I cannot see the errors. Also, please look at the closed issues, you may find similar issues.

**Comment by AZ1229-forever** [comment]
> 嗨，图片上传不正确。我看不到错误。另外，请查看已关闭的 issue，您可能会发现类似的 issue。
您好。
若直接运行会出现以下错误
ERROR:root:Can not find checkpoint for ./results/Oct-29_13-42-16/models/
若在终端运行会出现以下报错
Traceback (most recent call last):
  File "run_mappo.py", line 253, in <module>
    train(args)
  File "run_mappo.py", line 82, in train
    env = gym.make('merge-multi-agent-v0')
  File "D:\Anconda3\lib\site-packages\gym\envs\registration.py", line 569, in make
    _check_version_exists(ns, name, version)
  File "D:\Anconda3\lib\site-packages\gym\envs\registration.py", line 219, in _check_version_exists
    _check_name_exists(ns, name)
  File "D:\Anconda3\lib\site-packages\gym\envs\registration.py", line 197, in _check_name_exists
    raise error.NameNotFound(
gym.error.NameNotFound: Environment merge-multi-agent doesn't exist.
我查看了之前的issue，把highway—env设置成根目录，还是无法解决，我是MARL新手，可能请您看看是什么问题吗

**Comment by DongChen06** [comment]
You do not need to install the highway-env, as it is already included in the repo.

**Comment by AZ1229-forever** [comment]
> 您不需要安装 highway-env，因为它已经包含在存储库中。

您好，我并没有安装highway-env，或者是其他的原因。不好意思再问您一个问题，您会将论文中的算法开源吗，这对我的学习很有帮助，期待您的回答！

**Comment by DongChen06** [comment]
The codes were already in the readyme

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by AZ1229-forever** [comment]
感谢您的回答，但是我再次尝试运行，还是出现以下错误
Traceback (most recent call last):
  File "run_mappo.py", line 255, in <module>
    train(args)
  File "run_mappo.py", line 82, in train
    env = gym.make('merge-multi-agent-v0')
  File "D:\Anconda3\lib\site-packages\gym\envs\registration.py", line 569, in make
    _check_version_exists(ns, name, version)
  File "D:\Anconda3\lib\site-packages\gym\envs\registration.py", line 219, in _check_version_exists
    _check_name_exists(ns, name)
  File "D:\Anconda3\lib\site-packages\gym\envs\registration.py", line 197, in _check_name_exists
    raise error.NameNotFound(
gym.error.NameNotFound: Environment merge-multi-agent doesn't exist.

**Comment by AZ1229-forever** [comment]
您好，我尝试重新运行，先出现以下错误：
PS F:\MARL_AD_U-20241029T082951Z-001\MARL_AD_U\MARL> python run_ma2c.py
ERROR:root:Can not find checkpoint for ./results/Nov-01_20_14_40/models/

且一直处于运行状态，您可以指导一下问题出在何处吗

**Comment by DongChen06** [comment]
Hello, that's not an error. I think you can successfully run it now!
