### ISSUE TITLE
AttributeError: module 'gym' has no attribute 'wrappers'

### ISSUE THREAD

**Issue by fuwen666** [Derekabc/MARL_CAVs#7]
I got an error,
"(fuwen) wen@wen:~/Desktop/MARL_CAVs-main/MARL$ python run_mappo.py
Traceback (most recent call last):
  File "run_mappo.py", line 8, in <module>
    import highway_env
  File "/home/wen/anaconda3/envs/fuwen/lib/python3.6/site-packages/highway_env/__init__.py", line 5, in <module>
    import highway_env.envs
  File "/home/wen/anaconda3/envs/fuwen/lib/python3.6/site-packages/highway_env/envs/__init__.py", line 1, in <module>
    from highway_env.envs.highway_env import *
  File "/home/wen/anaconda3/envs/fuwen/lib/python3.6/site-packages/highway_env/envs/highway_env.py", line 5, in <module>
    from highway_env.envs.common.abstract import AbstractEnv
  File "/home/wen/anaconda3/envs/fuwen/lib/python3.6/site-packages/highway_env/envs/common/abstract.py", line 21, in <module>
    class AbstractEnv(gym.Env):
  File "/home/wen/anaconda3/envs/fuwen/lib/python3.6/site-packages/highway_env/envs/common/abstract.py", line 32, in AbstractEnv
    _monitor: Optional[gym.wrappers.Monitor]
AttributeError: module 'gym' has no attribute 'wrappers'
"

**Comment by DongChen06** [comment]
Hi, could you please check this issue https://github.com/Derekabc/MARL_CAVs/issues/2 to set up your experiment?

**Comment by fuwen666** [comment]
Thank you!

**Comment by fuwen666** [comment]
/home/wen/anaconda3/envs/fuwen/bin/python /home/wen/Desktop/MARL_CAVs-main/MARL/run_mappo.py
ERROR:root:Can not find checkpoint for ./results/Oct-19_05:12:30/models/
/home/wen/Desktop/MARL_CAVs-main/MARL/single_agent/Model_common.py:21: UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
  out = self.output_act(self.fc3(out))

**Comment by DongChen06** [comment]
have you solved the issue?  You can ignore the error above since it tries to load the pretrained weights.
