### ISSUE TITLE
TypeError: _reset() got an unexpected keyword argument 'num_CAV'

### ISSUE THREAD

**Issue by liuqi1998** [Derekabc/MARL_CAVs#9]
Hello. I run the "run_mappo.py", and it occurs this problem:

/home/liuqi/文档/MARL_CAVs-main/venv/bin/python /home/liuqi/文档/MARL_CAVs-main/MARL/run_mappo.py
Traceback (most recent call last):
  File "/home/liuqi/文档/MARL_CAVs-main/MARL/run_mappo.py", line 228, in <module>
    train(args)
  File "/home/liuqi/文档/MARL_CAVs-main/MARL/run_mappo.py", line 80, in train
    env = gym.make('highway-fast-v0')
  File "/home/liuqi/文档/MARL_CAVs-main/venv/lib/python3.6/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/liuqi/文档/MARL_CAVs-main/venv/lib/python3.6/site-packages/gym/envs/registration.py", line 90, in make
    env = spec.make(**kwargs)
  File "/home/liuqi/文档/MARL_CAVs-main/venv/lib/python3.6/site-packages/gym/envs/registration.py", line 60, in make
    env = cls(**_kwargs)
  File "/home/liuqi/文档/MARL_CAVs-main/highway-env/highway-env/envs/common/abstract.py", line 84, in __init__
    self.reset()
  File "/home/liuqi/文档/MARL_CAVs-main/highway-env/highway-env/envs/common/abstract.py", line 191, in reset
    self._reset(num_CAV=num_CAV)
TypeError: _reset() got an unexpected keyword argument 'num_CAV'

Process finished with exit code 1

I changed the "run_mappo.py", "env = gym,make('highway-fast-v0')", and I registed the "highway-fast-v0" in the "MARL_CAVs-main" project. How to solve this problem?

**Comment by DongChen06** [comment]
please check the usage of the _reset function.

**Comment by liuqi1998** [comment]
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Derekabc/MARL_CAVs"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月14日(星期二) 上午10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Derekabc/MARL_CAVs] TypeError: _reset() got an unexpected keyword argument 'num_CAV' (Issue #9)





 
please check the usage of the _reset function.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 
















And what should I do next?

**Comment by liuqi1998** [comment]
I checked the usage of the _reset function. In "abstract.py" line 191, "self._reset(num_CAV=num_CAV)", and in "registration.py" line 161, "env.reset=env._reset". What should I do next?
